# Generated by Django 6.0.4 on 2026-05-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='visits',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visits',
            name='status',
            field=models.CharField(default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='visits',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
